# railway.toml

[build]
  # Specify the build command if needed
  command = "poetry install"

[deploy]
  # Specify the deploy command if needed
  command = "poetry run python main.py"

[env]
  TELEGRAM_BOT_TOKEN = "7259089235:AAEwe-y7srP0lHKKrY-sNURTiUOP2lqaTjw"
  PROXY_FILE_PATH = "proxy.txt"
